services:
  nginx:
    build: ./nginx
    container_name: pet-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certbot/www:/var/www/certbot
      - ./hugo/site/public:/usr/share/nginx/html
      - ./nginx/certbot/conf:/etc/ssl
      
    depends_on:
      - hugo

  hugo:
    image: klakegg/hugo:ext-alpine
    container_name: pet-hugo
    restart: on-failure
    volumes:
      - ./hugo/site:/src
    command:
      --destination /src/public --watch --buildDrafts --verbose
